### ISSUE TITLE
CUDA_ERROR_INVALID_PTX

### ISSUE THREAD

**Issue by Uranite** [Gui-Yom/turbo-metrics#1]
Hi, I compiled https://github.com/Gui-Yom/turbo-metrics/commit/0ad1a3f2945d7a96a7b64f190ef376550187dc5a as per the documentation (had to add `C:\Users\username\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-msvc\bin` to path). After trying to run the resulting binary, this is the error that I'm getting.
![image](https://github.com/user-attachments/assets/b27f9bf1-c29e-4ea1-8060-735d2a6b0193)

**Comment by Gui-Yom** [comment]
Can you try to comment the first `rustflags` line and uncomment the second in `.cargo/config.toml` : 
```toml
[target.nvptx64-nvidia-cuda]
#rustflags = ["-Z", "unstable-options", "-C", "linker-flavor=llbc", "-C", "target-cpu=sm_89", "-Z", "tune-cpu=sm_89"]
rustflags = ["-Z", "unstable-options", "-C", "linker-flavor=llbc"]
```

Or try to replace sm_89 with sm_86.

Also, can you verify the content of the ptx files like `target/nvptx64-nvidia-cuda/release-nvptx/cuda_colorspace_kernel.ptx` ?
